### ISSUE TITLE
line-height (space between the lines) is too small

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#13]
As a user i would like to have the option to configure the line-height to enhance readability.
Alternativeley this issue would be solved for me if the line-height would be increased hardcoded by 50%.

**Comment by yydcdut** [comment]
You mean `android:lineSpacingExtra` or `android:lineSpacingMultiplier` ?

**Comment by stefan-niedermann** [comment]
Err, don't know, i think the correspondenting code lines are this: https://github.com/yydcdut/RxMarkdown/blob/master/rxmarkdown/src/main/java/com/yydcdut/rxmarkdown/span/MDHorizontalRulesSpan.java#L74-L75

Current behavior:

![expected](https://cloud.githubusercontent.com/assets/4741199/21450514/25eae894-c8f8-11e6-9159-3be5320d71c6.png)

Expected behavior:

![expected](https://cloud.githubusercontent.com/assets/4741199/21450539/5bd90fc6-c8f8-11e6-9f08-11595187b3c9.png)

**Comment by yydcdut** [comment]
horizontal rules height?

**Comment by stefan-niedermann** [comment]
Damnit, i messed it up with #14

**Comment by stefan-niedermann** [comment]
I didn't use lineSpacing in android yet, but i think what i am trying to say is:
`android:lineSpacingMultiplier` should be 1.5

The according CSS-syntax ([Example](http://www.w3schools.com/cssref/tryit.asp?filename=trycss_line-height)) would be `line-height: 150%;`

**Comment by korelstar** [comment]
This is a comparison of 1 (left) and 1.15 (right): http://vickychijwani.me/content/images/2015/11/popular-movies-cramped-text.png

I think, the right one (1.15) would be a good default.

**Comment by stefan-niedermann** [comment]
yeap

**Comment by yydcdut** [comment]
eh, yes, `android:lineSpacingMultiplier`

**Comment by stefan-niedermann** [comment]
@yydcdut has this been fixed by a new option? if yes: how to use it? or has this been fixed by increasing the `lineSpacingMultiplier` globally?

**Comment by yydcdut** [comment]
lineSpacingMultiplier
