### ISSUE TITLE
horizontal ruler (---) is too fat

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#14]
As a user i would like to have the option to configure the height of a horizontal ruler to enhance the design.
Alternativeley this issue would be solved for me if the height would be decreased hardcoded to 1px.

**Comment by yydcdut** [comment]
Thanks for your suggestions, I will do it these days!

**Comment by stefan-niedermann** [comment]
Err, don't know, i think the correspondenting code lines are this: https://github.com/yydcdut/RxMarkdown/blob/master/rxmarkdown/src/main/java/com/yydcdut/rxmarkdown/span/MDHorizontalRulesSpan.java#L74-L75

Current behavior:

![expected](https://cloud.githubusercontent.com/assets/4741199/21450514/25eae894-c8f8-11e6-9159-3be5320d71c6.png)

Expected behavior:

![expected](https://cloud.githubusercontent.com/assets/4741199/21450539/5bd90fc6-c8f8-11e6-9f08-11595187b3c9.png)

Edit: maybe use better a slightly darker color.
