### ISSUE TITLE
EditText: continue lists with the used sign

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#16]
**Given** you are start edit a given Markdown snippet with a list using the `-`-sign
**When** you press `Enter` to start a new line / new list item
**Then** the library should start the new list item with the sign that has been used in the list before.

**Current behavior:**

`*`-sign is used always for new list items
![unbenannt](https://cloud.githubusercontent.com/assets/4741199/21346926/c6ea5f80-c6a6-11e6-9095-e9a334782b13.png)

**Comment by yydcdut** [comment]
fix 0.1.0
