### ISSUE TITLE
Stop creating new list items on multiple Enter-presses

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#17]
**Given** you edited a list and want to continue with a normal paragraph. You press `Enter`, a new list item is generated (using a `*`-sign). 
**When** you do not enter anything but press enter again
**Then** the empty list template (The `*`-sign) should be removed and a empty line should be inserted to enable the user to go ahead with a normal paragraph.

**Current behavior**
If you press enter x times, there are generated x new empty list items

![unbenannt](https://cloud.githubusercontent.com/assets/4741199/21347186/d3b558e0-c6a7-11e6-9a12-fd193214e9ee.png)

**Comment by stefan-niedermann** [comment]
This behavior seems to be fixed in the current version - thank you!

**Comment by stefan-niedermann** [comment]
Thus affects ordered lists, too. Can you please fix that, too? :)

**Comment by yydcdut** [comment]
Fix it at this weekend.
Sorry, I'm busy with company job these days.

**Comment by stefan-niedermann** [comment]
> Sorry, I'm busy with company job these days.

Absolutely no problem - we all know that :)
