### ISSUE TITLE
Demo 卡顿

### ISSUE THREAD

**Issue by Yanqilong** [yydcdut/RxMarkdown#22]
RxMDEditText内， 上下滑动卡顿，没有了滑动惯性

**Comment by yydcdut** [comment]
普通的EditText也没有滑动惯性

**Comment by Yanqilong** [comment]
搜嘎，但是文本一长，拖动好困难，有没有办法优化， 我还发现了一个问题，开启了实时预览模式，如果预选输入文字，再点击工具栏应用样式，ok没问题， 如果在空白处点样式，后面输入的文本没有样式呈现

**Comment by yydcdut** [comment]
当文本长的时候想拖动不困难的话，可以尝试重写一写onTouchEvent方法吧，判断文本长度是否大于控件长度，如果可以发生滑动，马上把EditText的焦点取消或者转到父控件里面，当滑动停了再让EditText获取焦点。

**Comment by Yanqilong** [comment]
谢谢大大思路

**Comment by yydcdut** [comment]
诶，我发现外面套一层ScrollView就能解决这个问题了    ╮(╯▽╰)╭
