### ISSUE TITLE
Pasting images

### ISSUE THREAD

**Issue by RedLann** [yydcdut/RxMarkdown#24]
Hello, im trying to use the edittext widget, i need users to be able to past images (copied from webpage in chrome) into it but the images are pasted as a green/azure square with the DefaultLoader. Is there any way to get the images correctly when pasted?

**Comment by yydcdut** [comment]
images? not urls?

**Comment by RedLann** [comment]
I'm talking about when i paste something in the editor, if i copy text+images from chrome and then paste it in the editor i get some squares instead of the image (or url).
