### ISSUE TITLE
Workflow proposals

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#30]
Dear @yydcdut,

please do not misunderstood this request as critic. For the outstanding people it would be very helpful to

- tag your versions with the git tagging system (e. g. `git tag 0.1.0`)
- write all your issues in english

Outstanding people can not help implement features or fix bugs, if they do not understand what's the issue.

Regards

**Comment by yydcdut** [comment]
Haha, ok, thank you!
