### ISSUE TITLE
URLSpans don't work properly

### ISSUE THREAD

**Issue by cesards** [yydcdut/RxMarkdown#32]
If we got:
```
This is another [link](http://deathstar-qa.herokuapp.com/reporting) please
```
It's not printing the url span properly, it just prints the text.

I've checked the code, and also I've been retrieving the spans, and it seems the span is there
`URLSpan[] spans = stringBuilder.getSpans(0, charSequence.length(), URLSpan.class);`
but it's not being drawn properly:

![screenshot_20170403-163147](https://cloud.githubusercontent.com/assets/1536079/24617210/3c2301d6-188b-11e7-89be-eb36c9ec4cdb.png)

**Comment by cesards** [comment]
It just prints the text.

**Comment by yydcdut** [comment]
Did you set 
```java
setLinkColor(Color.BLUE)
setLinkUnderline(false)
```
in `RxMDConfiguration.Builder`?

**Comment by cesards** [comment]
Yep. Nothing happens:
```
RxMDConfiguration rxMDConfiguration = new RxMDConfiguration.Builder(this)
        .setLinkColor(Color.RED)//default color of link text
        .setLinkUnderline(false)//default value of whether displays link underline
        .build();

    RxMarkdown.with(newsItemUI.getText(), this)
        .config(rxMDConfiguration)
        .factory(TextFactory.create())
        .intoObservable()
        .subscribeOn(Schedulers.computation())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Subscriber<CharSequence>() {
          @Override
          public void onCompleted() { }

          @Override
          public void onError(Throwable e) { }

          @Override
          public void onNext(CharSequence charSequence) {
            view.text.setText(charSequence, TextView.BufferType.SPANNABLE);
          }
        });
```
where `newsItemUI.getText()` is:
```
[PLEASEEEEEE](http://deathstar-qa.herokuapp.com/)
```
and the output of `onNext` is:
```
PLEASEEEEEE
```

**Comment by VovaStelmashchuk** [comment]
@cesards Can you attached your xml file and class of your view?

**Comment by cesards** [comment]
I found the problem!

The problem is related to the flag:
`android:autoLink="web"`
because the TextView removes all the Spans, I guess, and it creates its own.

You should mention that in the documentation. Thank you so much, guys!
