### ISSUE TITLE
Check-Boxes in every line-start of long paragraph

### ISSUE THREAD

**Issue by treborxy** [yydcdut/RxMarkdown#42]
I use Android App "Nextcloud Notes" (https://github.com/stefan-niedermann/nextcloud-notes).
## Problem:
In view-mode you get a checkbox at every line's start within a long paragraph when viewing on small devices which force line-breaks.

>>> start snip
# Test ToDo
- [ ] lore ipsum infernalis lore ipsum infernalis lore ipsum infernalis
>>> stop snip

## Steps to reproduce the issue:
Android version:** 7.1.2 LineageOs
Device: Sony Xperia Z
System language: German
App version: 0.1.21
App source: F-Droid

- open the app
- click on a note
- use the edit button
- insert long text with checkbox

**Comment by yydcdut** [comment]
Hi, after reading this issue, I think what you mean is that you don't want to break the line if the text is long?

**Comment by stefan-niedermann** [comment]
I think it is more about a checkbox is rendered at every line-break

![screenshot_notizen_20180518-110753](https://user-images.githubusercontent.com/4741199/40226370-d1c1326a-5a8b-11e8-9837-ad1e59ab5f87.png)

![screenshot_notizen_20180518-110758](https://user-images.githubusercontent.com/4741199/40226377-d66d89ee-5a8b-11e8-9319-2ca8d0e13545.png)

**Comment by yydcdut** [comment]
get it!
