### ISSUE TITLE
不是livephoto的demo吗

### ISSUE THREAD

**Issue by WM520** [yydcdut/RxMarkdown#47]
根据博文过来的，现在想做livephoto ，希望博主指点江山

**Comment by yydcdut** [comment]
你给个邮箱，我晚上把之前的代码发你

**Comment by WM520** [comment]
1071597946@qq.com,感谢大大

**Comment by yydcdut** [comment]
对不起啊兄弟，翻了下电脑代码好像已经删掉了

**Comment by WM520** [comment]
好吧，，，感谢

**Comment by WM520** [comment]
还能有实现的思路不

**Comment by yydcdut** [comment]
@WM520 
https://github.com/0359xiaodong/LivePhotos-android
