### ISSUE TITLE
Rendering of **Text**

### ISSUE THREAD

**Issue by DBetta** [yydcdut/RxMarkdown#6]
The Library is really working well and appreciate its responsiveness compared to other MarkDown renders I've interacted with. But, I have encountered problem while rendering bold text of the form **Text**

**Comment by yydcdut** [comment]
eh, can you tell me a little more？

**Comment by DBetta** [comment]
I have tried to parse this text but renders as it is in android textview.

`**To all gentlemen**. The **hike** is coming up **this Saturday**`

**Comment by DBetta** [comment]
Hi. I've u figured the problem?

**Comment by yydcdut** [comment]
I see that it's correct in `RxTextView`, but something wrong with `RxEditText`

**Comment by DBetta** [comment]
There some instances when it does not render correctly.

**Comment by DBetta** [comment]
If you can help out the better am working on a project and currently am
overwhelmed by other parts to check on the cause please.

**Comment by yydcdut** [comment]
But it's correct in android textview for rendering of **bold**, i can't reproduce this bug
