### ISSUE TITLE
Some style issues

### ISSUE THREAD

**Issue by stefan-niedermann** [yydcdut/RxMarkdown#8]
Hi @yydcdut,
first of all: thanks for this great lib! I am planning to use it in the [Nextcloud Notes](https://github.com/stefan-niedermann/OwnCloud-Notes/tree/RxMarkdown)-app.
Currently i am struggling with [some style issues](https://github.com/stefan-niedermann/OwnCloud-Notes/issues/2#issuecomment-266115838) we experienced while testing.
Maybe these style issues could be fixed or at least a configuration option could be provided by you for these?

- [x] **1.) Headings in TextView have a padding or margin on the left side:** (fixed in  #10)

![hadings](https://cloud.githubusercontent.com/assets/4741199/21072267/ba280eba-bebc-11e6-927c-04ae5140cb8c.png)

Expected behavior: There is no padding or margin or there is a configuration to disable it or set it to zero.

- [ ] **2.) Very long quotes (`> Text`) that do not fit into  a single line crash on the grey border (TextView && EditView)**

![quote](https://cloud.githubusercontent.com/assets/4741199/21072283/1f343f2c-bebd-11e6-9e16-54604d1352be.png)

Expected behavior: Even if the line breaks because it does not fit into a single row the padding/margin on the left side should be equal to the first line.
Bonus: Make the padding configurable (i personally would like to have some more padding here)

**Comment by korelstar** [comment]
Made a pull request (#10) for 1.)

I think, most of 2.) is already fixed in the `master` branch. So a new release would be nice :smiley:

**Comment by stefan-niedermann** [comment]
Hi @yydcdut, i split the two minor issues out to two seperate issues (#13, #14) to make it easier for you to release a new version and close this one issue :)
This would bring much benefit to us and allows you to work on the other issues decoupled.
Regards

**Comment by stefan-niedermann** [comment]
Hey @yydcdut any progress on the opened issues? :)

**Comment by stefan-niedermann** [comment]
@yydcdut did you have time to have a look at the issues? according to @korelstar this issue should be fixed already and only a new release is necessary. I would be glad to provide help (e. g. testing).

Regards

**Comment by yydcdut** [comment]
Sorry, I update 0.0.8-beta.

**Comment by stefan-niedermann** [comment]
Seems to be fixed :) Great.
